// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "web-service-gin/internal/products/domain"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *Service) GetAll(ctx context.Context) ([]domain.Produtos, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Produtos
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Produtos); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Produtos)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOne provides a mock function with given fields: id
func (_m *Service) GetOne(id int) (domain.Produtos, error) {
	ret := _m.Called(id)

	var r0 domain.Produtos
	if rf, ok := ret.Get(0).(func(int) domain.Produtos); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Produtos)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: produto
func (_m *Service) Store(produto domain.ProdutoRequest) (domain.Produtos, error) {
	ret := _m.Called(produto)

	var r0 domain.Produtos
	if rf, ok := ret.Get(0).(func(domain.ProdutoRequest) domain.Produtos); ok {
		r0 = rf(produto)
	} else {
		r0 = ret.Get(0).(domain.Produtos)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.ProdutoRequest) error); ok {
		r1 = rf(produto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, produto
func (_m *Service) Update(id int, produto domain.ProdutoRequest) (domain.Produtos, error) {
	ret := _m.Called(id, produto)

	var r0 domain.Produtos
	if rf, ok := ret.Get(0).(func(int, domain.ProdutoRequest) domain.Produtos); ok {
		r0 = rf(id, produto)
	} else {
		r0 = ret.Get(0).(domain.Produtos)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.ProdutoRequest) error); ok {
		r1 = rf(id, produto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateName provides a mock function with given fields: id, name
func (_m *Service) UpdateName(id int, name string) (string, error) {
	ret := _m.Called(id, name)

	var r0 string
	if rf, ok := ret.Get(0).(func(int, string) string); ok {
		r0 = rf(id, name)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(id, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
