version: '3.9'

services:
  mariadb:
    image: mariadb:10.8.3
    container_name: bootcamp-database
    hostname: bootcamp-database
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - ./.data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
